# Generated by Django 4.2 on 2025-06-09 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_files', '0004_alter_system_files_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.JSONField()),
                ('comment_date', models.CharField(max_length=100)),
                ('approver', models.CharField(max_length=100)),
                ('requester', models.CharField(max_length=100)),
                ('file_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system_files.system_files')),
            ],
        ),
    ]
