# Generated by Django 4.2 on 2025-06-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System_Files',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('system', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='files/')),
                ('author', models.CharField(max_length=100)),
                ('signature_status', models.CharField(max_length=100)),
                ('approval_status', models.CharField(max_length=100)),
                ('qrcode', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
            ],
        ),
    ]
