# Generated by Django 4.2 on 2025-06-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_files',
            name='approval_status',
            field=models.CharField(choices=[('Signed', 'Signed'), ('Not signed', 'Not signed')], default='Not signed', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_files',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='system_files',
            name='qrcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='system_files',
            name='signature_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_files',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
