# Generated by Django 4.2 on 2025-06-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_files', '0002_alter_system_files_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_files',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Not signed', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_files',
            name='signature_status',
            field=models.CharField(choices=[('Signed', 'Signed'), ('Not signed', 'Not signed')], default='Pending', max_length=100),
        ),
    ]
