# Generated by Django 4.2 on 2025-06-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_files', '0003_alter_system_files_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_files',
            name='created_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='system_files',
            name='modified_date',
            field=models.CharField(max_length=10),
        ),
    ]
