# Generated by Django 4.2 on 2025-06-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_files', '0005_system_files_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_files',
            name='file_type',
            field=models.CharField(max_length=100),
        ),
    ]
